#==========================================================================
# Description: 专用打包 N1(s905d) OpenWrt 固件
# 固定：N1(s905d) + 内核6.12.y + IP 192.168.2.15
#==========================================================================

name: build-openwrt-image

on:
  workflow_dispatch:
    inputs:
      openwrt_rootfs_url:
        description: 输入 rootfs 直链
        required: true
        default: "https://downloads.openwrt.org/releases/24.10.6/targets/armsr/armv8/openwrt-24.10.6-armsr-armv8-rootfs.tar.gz"

env:
  TZ: Etc/UTC

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Initialize environment
        run: |
          sudo apt-get update
          sudo apt-get install -y $(curl -fsSL https://ophub.org/ubuntu2404-make-openwrt-depends)

      - name: Create virtual disk
        run: |
          sudo mkdir -p /builder
          sudo mount -t tmpfs -o size=15G tmpfs /builder
          cd /builder
          mkdir download

      - name: Download your rootfs
        working-directory: /builder
        run: |
          curl -fsSL "${{ inputs.openwrt_rootfs_url }}" -o download/openwrt-rootfs.tar.gz

      - name: Package N1 (s905d) Firmware
        uses: unifreq/openwrt_packit@master
        env:
          OPENWRT_ARMSR: /builder/download/*.tar.gz
          PACKAGE_SOC: s905d
          KERNEL_VERSION_NAME: 6.12.y
          OPENWRT_IP: 192.168.2.15
          KERNEL_AUTO_LATEST: true
          KERNEL_REPO_URL: ophub/kernel

      - name: Upload to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS == 'success' }}
        with:
          tag: N1_OpenWrt
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
